PREFIX rso: <http://www.fortiss.org/diprolea/ontosustain/rso#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX qudt: <http://qudt.org/schema/qudt/>
SELECT ?indicator ?unit WHERE {
     rso:Indicator23_305-1-a  qudt:hasUnit ?u;
                              rdfs:label ?indicator .
    ?u a qudt:Unit ;
       rdfs:label ?unit.
    FILTER(LANGMATCHES(LANG(?unit), "en"))
}