PREFIX rso: <http://www.fortiss.org/diprolea/ontosustain/rso#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?topic WHERE {
    {
        rso:Indicator87_E1-6-45-a rso:measuresGRITopic ?t .
        ?t a rso:GRITopic.
    }
    UNION
    {
        rso:Indicator87_E1-6-45-a rso:measuresESRSTopic ?t .
        ?t a rso:ESRSTopic.
    }
    ?t a rso:Topic ;
       rdfs:label ?topic .
}
